name: cons_calc_lib
description: Test library for MPower.
version: 0.0.1
author: Sergio Sanchez <sergio@mpower.africa>
homepage: https://www.mpower.africa/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  circular_profile_avatar: ^1.0.6
  material_design_icons_flutter: ^4.0.5145

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: